# gen_entity_types.py

import re
import os
import os.path

entity_types_dir="src/entity_types/"
include_dir="include/"

pattern = re.compile("void\s+(init|update|destroy)_(\w+)")
matches = []

for filename in os.listdir(entity_types_dir):
  if os.path.isfile(entity_types_dir + filename):
    with open(entity_types_dir + filename, "r") as f:
      matches += pattern.findall(f.read())

with open(include_dir + "entity_types_gen.h", "w") as header:
  header.write("// entity_types_gen.h -- generated by gen_entity_types.py\n\n")
  for match in matches:
    header.write("void " + match[0] + "_" + match[1] + "(struct Entity*);\n")
